### ISSUE TITLE
Agregar vistas de Business

### ISSUE THREAD

**Issue by matiasquevedo** [Lucas-69/canchas#9]
Crear la carpeta de vistas business dentro de /resources/views/admin.
Crear dentro de business las vistas:

- create.blade.php

- edit.blade.php

- show.blade.php

- index.blade.php

Extender todas las vistas de la plantilla main con le codigo:
@extends('admin.template.main')

agregar el titulo en la pestaña segun conrresponda.
cada vista lleva un div con la clase container, donde se incluira el contenido de la vista

**Comment by matiasquevedo** [comment]
![captura de pantalla de 2018-08-27 09-48-39](https://user-images.githubusercontent.com/12038889/44662895-6b716a80-a9e5-11e8-8017-540f2a666c51.png)

Ese código no hace falta... hasta que veamos como vamos a indexar las empresas. Por ahora dejar las vistas con un div.container

**Comment by matiasquevedo** [comment]
![captura de pantalla de 2018-08-27 09-49-22](https://user-images.githubusercontent.com/12038889/44662981-99ef4580-a9e5-11e8-901d-9277631faf9b.png)

use App\Business; hacer referencia al modelo. No hay que incluirlo hasta que se vaya a usar en el controlador.

**Comment by matiasquevedo** [comment]
Pull Request and merge #16

**Comment by Lucas-69** [comment]
ya correji los detalles de las vistas y el controllador de business
